Web stack/NerdCooking/Demo3/Finished/NerdCooking/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NerdCooking.Models;

namespace NerdCooking.Controllers
{
    public class HomeController : Controller
    {
        private IWorkshopRepository _workshopRepository;

        public HomeController()
        {
            _workshopRepository = new WorkshopRepository();
        }

        public HomeController(IWorkshopRepository workshopRepository)
        {
            _workshopRepository = workshopRepository;
        }

        //
        // Action: /Home/
        public ViewResult Index()
        {
            return View(new IndexViewModel
            {
                UpcomingWorkshops = _workshopRepository.GetUpcomingWorkshops()
            });
        }

        //
        // Action: /Home/PageNotFound
        public ActionResult PageNotFound()
        {
            return View();
        }

        //
        // Action: /Home/GeneralError
        public ActionResult GeneralError()
        {
            return View();
        }
    }
}

Web stack/NerdCooking/Demo3/Finished/NerdCooking/Controllers/WorkshopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using NerdCooking.Models;

namespace NerdCooking.Controllers
{
    public class WorkshopsController : Controller
    {
        private IMembershipRepository _membershipRepository;
        private IWorkshopRepository _workshopRepository;
        
        public WorkshopsController()
            :this(new MembershipRepository(), new WorkshopRepository())
        {
        }

        public WorkshopsController(IMembershipRepository membershipRepository, IWorkshopRepository workshopRepository)
        {
            _membershipRepository = membershipRepository;
            _workshopRepository = workshopRepository;
        }

        //
        // GET: /Workshops/Create
        [Authorize(Roles = "Organizer")]
        public ActionResult Create()
        {
            return View(new Workshop());
        }

        //
        // POST: /Workshops/Create
        [HttpPost]
        [Authorize(Roles = "Organizer")]
        public ActionResult Create(Workshop workshop)
        {
            try
            {
                // Automatically create reservations for the members in the application
                // that are not marked as optional and are confirmed
                foreach (var membership in _membershipRepository.GetMemberships())
                {
                    Reservation reservation = new Reservation();
                    reservation.UserName = membership.UserName;

                    workshop.Reservations.Add(reservation);
                }

                // Save the workshop to the database
                _workshopRepository.InsertOrUpdate(workshop);
                _workshopRepository.Save();

                return RedirectToAction("Details", new { id = workshop.Id });
            }
            catch (Exception)
            {
                return View(workshop);
            }
        }

        //
        // GET: /Workshops/Details/id
        public ViewResult Details(int id)
        {
            var workshop = _workshopRepository.Find(id);
        	return View(workshop);
        }
    }
}

Web stack/NerdCooking/Demo3/Finished/NerdCooking/Views/Home/GeneralError.cshtml
@{
    ViewBag.Title = "general error";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container_12 clearfix" id="content">
    <div class="grid_8">
        <h2>Oh, euhm, something must have gone really bad there</h2>
        <p>OKay, I admit, I screwed up. Might be really bad, but it could also be fixed in a few seconds.
        My suggestion: Try, try again. Or maybe</p>
        <ul>
            <li>Get me more coffee so I go fix it.</li>
            <li>Buy a roll of ducktape and hope for the best</li>
            <li>Feel sorry for me and browse other websites on the interwebs</li>
        </ul>
    </div>
</div>

Web stack/NerdCooking/Demo3/Finished/NerdCooking/Views/Home/Index.cshtml
@model NerdCooking.Models.IndexViewModel
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container_12 clearfix" id="content">
    <div class="grid_9">
        <h2>Upcoming workshops</h2>
        @foreach (var workshop in Model.UpcomingWorkshops)
        {
            Html.RenderPartial("~/Views/Shared/_WorkshopListItem.cshtml", (NerdCooking.Models.Workshop)workshop);
        }

    </div>

    <div class="grid_3">
        <h2>About</h2>
        <p>Nerd cooking is a sample application that was originally produced to demonstrate.
        Just how much fun ASP.NET and HTML5 can be. It's not complete, far from it, but what 
        else did you expect from a demo application?</p>
        <p>Have a look around and <a href="mailto:willemm@infosupport.com">let me know</a> if you have any questions.</p>
    </div>
</div>

<div class="container_12 clearfix" id="content-after">
    <div class="grid_6">
        <h2>Organize a workshop</h2>
        <p>Want to cook up something nice? Organize a new workshop!</p>
        @using (Html.BeginForm("Create", "Workshops", FormMethod.Post))
        {
        <div class="editor-label">
            <label for="date">Title:</label>
        </div>
        <div class="editor-field">
            <input type="text" id="Title" name="Title" />
        </div>
        <div class="editor-label">
            <label for="date">Date:</label>
        </div>
        <div class="editor-field">
            <input type="date" id="Date" name="Date"/>
        </div>
        <div class="editor-label">
            <label for="Description">Description:</label>
        </div>
        <div class="editor-field">
            <textarea id="Description" name="Description"></textarea>
        </div>
        <div class="editor-label">
            <input type="submit" value="Organize" />
        </div>
        }
    </div>
    <div class="grid_6">
        <h2>Statistics</h2>
        <p>Here's a few statistics to satisfy your inner nerdness</p>
        <ul>
            <li>
                <span>Number of workshops organized: </span>
                <span>2</span>
            </li>
            <li>
                <span>Upcoming number of workshops: </span>
                <span>2</span>
            </li>
            <li>
                <span>Number of members: </span>
                <span>2</span>
            </li>
        </ul>
    </div>
</div>

Web stack/NerdCooking/Demo3/Finished/NerdCooking/Views/Home/PageNotFound.cshtml
@{
    ViewBag.Title = "Page not found";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container_12 clearfix" id="content">
    <div class="grid_8">
        <h2>Page could not be found</h2>
        <p>Whoops, Bob ran off with this page and he's not going to give it back. 
        Although he is my virtual goldfish he's still a vicious monster and is probably eating the page right now.</p>
        <p>Best thing you can do is go back to the homepage and try to get to the location you wanted again. If that doesn't work
        here's a few things you can try</p>
        <ul>
            <li>Get a cat and attack Bob head-on</li>
            <li>E-mail me, explain me that Bob isn't real and ask me where the page is </li>
            <li>Laugh really hard and move along.</li>
        </ul>
    </div>
</div>